# Generated by Django 4.2.7 on 2023-12-06 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims_app.subject')),
            ],
            options={
                'db_table': 'paper',
            },
        ),
        migrations.CreateModel(
            name='authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims_app.paper')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sims_app.user')),
            ],
            options={
                'db_table': 'authorship',
            },
        ),
    ]
