# Generated by Django 4.2.7 on 2023-12-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sims_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
