# Generated by Django 4.2.7 on 2023-12-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
