# Generated by Django 4.2.7 on 2023-12-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims_app', '0002_rename_data_added_subject_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='publication_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
