# Generated by Django 4.2.7 on 2023-12-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims_app', '0003_alter_paper_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
